### ISSUE TITLE
The diversity over merit one

### ISSUE THREAD

**Issue by ofpiyush** [frag-o-matic/TheLalaList#3]
The hiring can be called sexist.

It never says that they're going to settle for lower merit. 

Is there some information I'm missing?

**Comment by frag-o-matic** [comment]
makes sense, for now, did not edit it. Retained as it was in PR :)

**Comment by ofpiyush** [comment]
I believe that's a very dishonest thing to do.

Isn't part of what you do is vet PRs?

And now you've closed this issue without resolving the underlying problem.

**Comment by frag-o-matic** [comment]
> Isn't part of what you do is vet PRs?
Yes. I will vet only to make sure the proof is proper. I will not editorialize the PR content itself.

> And now you've closed this issue without resolving the underlying problem.
The problem I set out to solve was compile a list of companies with questionable culture. So far, I believe that is going fine (although a bit slow).

**Comment by frag-o-matic** [comment]
> One.

there are more, if you look closely see: https://twitter.com/__namc/status/829276174362755074
original tweet since deleted.

> One troll answer.

Don't care much for trolls. Point is no clear reply from OP anywhere in that thread stating position is open to everyone, not just women.

> At this moment it looks like you/this repo assumes women can not be equal in merit.

I did not assume anything of the sort. I just accepted a PR with public proof that is out there for the world to see.

> I think you've probably become an unwilling complicit in that line of thought.

... or it is just you wanting me to think that.

**Comment by ofpiyush** [comment]
> I did not assume anything of the sort.

`unwilling` was to point out that you probably don't understand what that statement with that tweet is implying there.

**Comment by sgaurav** [comment]
> Point is no clear reply from OP anywhere in that thread stating position is open to everyone, not just women.

I am assuming you read the tweet with a blood-eyed rage and missed the point that position was open only for `women` developers. She made it pretty clear there.

What she missed saying is that she is unwilling to accept sub-par candidates but given she is spending precious years of her life building MSD, I am assuming that to be the only case.

> I will vet only to make sure the proof is proper.

And that is exactly where you are failing in this case. When you are publically naming and shaming companies, the right way forward is _Presumption of innocence_ and not the other way around.

Since you are only vetting on existing of proof and unwilling to make judgements, come up with a voting mechanism and let the mass decide. But till then, steer clear of the ones you are unsure about.

While I support the existence of this list, it'd be beneficial if you took off your rose-tinted dev glasses and fully understood the problems and challenges faced in scaling up a team and culture. Diversity is an issue that needs to be solved while scaling even if it comes at the cost of waiting for one extra month to close that key position.

The benefit of having a diverse team and the effect it casts on your product far outweigh the extra effort put while building that team.

So, I'd suggest, look around and talk to people who have built and scaled teams before and understand challenges and issues one faces. And then, next time when you receive a PR, assume the best intentions from the founder, slip in his shoes and try to understand the situation before making an addition to this list.

But if you decide to not do any of this then this list is nothing more than a bunch CJing on anything they can dis about.

**Comment by frag-o-matic** [comment]
> that position was open only for women developers

which is precisely what the PR says: diversity over merit. When one is unwilling to interview a significant portion of the candidate pool, that says a lot about culture and hiring at a given place

> come up with a voting mechanism and let the mass decide

sure... that has worked out great for reddit and other social media

> Diversity is an issue that needs to be solved 

Yes, but I don't see how discrimination is the solution to it

**Comment by ofpiyush** [comment]
> diversity over merit.

Assuming N genders, there are N+1 cases that can happen. 

For 2, men and women, there are three cases.

Case 1: Women and men are equal in merit.

Case 2: Women are better than men in merit.

Case 3: Men are better than women in merit.

Only in case 3, the line `diversity over merit` holds true.

In all the cases, sexism holds true.

If you call it out for sexism, it makes sense. For `diversity over merit`, you're assuming case 3, which is very flawed to say the least.

**Comment by frag-o-matic** [comment]
Did you consider Case 4 : Forced diversity - artificially restricting hiring or recruitment to specific gender without regards to merit? aka diversity over merit. For it to be sexism, one would have to prefer a given gender _irrespective_ of merit, which one can argue, is implied to some extent by OPs tweet.

**Comment by ofpiyush** [comment]
> one can argue, is implied to some extent by OPs tweet.

Only if you ignore half the tweet.

>> 1 of the most challenging roles

In this weird dissection of a 2 line tweet, you're choosing to ignore that statement altogether.

That line clearly means merit is of very high value here.

> Case 4 : Forced diversity, without regards to merit

I didn't pick this case because of the quote above. Add it for completeness and still, you'd only be correct in half the cases.

Sexism(favouring one gender over the other), though, holds true in all 4, why not correct the error?

**Comment by frag-o-matic** [comment]
> Only if you ignore half the tweet.

yes, hence I did not include Sexism in the tweet on the list on anywhere.

> you're choosing to ignore that statement altogether.

that statement doesn't bear weight here, unless you wish to imply a specific gender would perform poorly in "challenging roles"

> Sexism(favouring one gender over the other), though, holds true in all 4, why not correct the error?

IMO "sexism" doesn't really apply unless there is a proof of equal merit _AND_  one were to prefer one gender over another. However, when one restricts a significant chunk of the candidate pool _BEFORE_ establishing merit, it clearly is a case of preferring diversity without regards to merit.

**Comment by ofpiyush** [comment]
> unless you wish to imply a specific gender

That is the one line that is related to `merit`. Challenging role means junior folks need not apply, i.e. one needs solid merit and people skills to be in that position. (especially devops)

>  BEFORE establishing merit

Every hire is not a new selection from an unknown pool. You mostly know the average, best and worst you can get given your company's rep and budget.

Nevertheless, your initial response led me to believe you didn't believe it to be true but accepted the PR in the glee of having started this useful repo.

As you've clarified that you stand by the derived meaning, I have nothing else to contribute.

☮️

**Comment by frag-o-matic** [comment]
> You mostly know the average, best and worst you can get given your company's rep and budget.

Yes, and cutting that already limited pool down on factors other than merit makes it questionable hiring.

> I have nothing else to contribute

Sorry to have wasted your time. :)
